install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
penguins = data.frame(penguins)
mean(penguins$body_mass_g, na.rm = TRUE)
head(penguins)
summary(penguins)
boxplot(bill_depth_mm ~ sex, data = penguins, main = "Penguin Bill Length vs. Sex", xlab = "Sex", ylab = "Bill Length")
require(here)
png(filename - here("Penguin_Boxplot.png"), width = 800, height = 600)
boxplot(bill_depth_mm ~ sex, data = penguins, main = "Penguin Bill Length vs. Sex", xlab = "Sex", ylab = "Bill Length")
dev.off()